name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-ssh-key.pem
          chmod 600 /tmp/ec2-ssh-key.pem

      - name: Sync files to EC2
        run: |
          rsync -avz --delete -e "ssh -i /tmp/ec2-ssh-key.pem" \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='ec2-ssh-key.pem' \
            ./src/ \
            ./nginx/default.conf \
            ./alembic.ini \
            ./docker-compose.yml \
            ./src/requirements.txt \
            ./.dockerignore \
            ./.env \
            ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
