name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Debug SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-ssh-key.pem
          chmod 600 ec2-ssh-key.pem
          ssh-keygen -y -f ec2-ssh-key.pem

      - name: Copy code to EC2 instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/my-app" # Ensure this path matches your app structure
          debug: true # Enable debug mode

      - name: SSH into EC2 and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/my-app
            # Update package list and install dependencies
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install -r src/requirements.txt
            # Start the FastAPI application
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: smiles_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U admin -d smiles_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    env:
      DB_HOST: localhost
      DB_PORT: "5433"
      DB_USER: admin
      DB_PASSWORD: 1234
      DB_NAME: smiles_db
      REDIS_HOST: localhost
      REDIS_PORT: "6379"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install redis-tools
        run: sudo apt-get install -y redis-tools

      - name: Wait for services
        run: |
          until pg_isready -h localhost -p 5433 -U admin; do
            echo "Waiting for Postgres..."
            sleep 2
          done
          until redis-cli -h localhost -p 6379 ping | grep -q "PONG"; do
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Run database migrations
        run: |
          alembic upgrade head

      - name: Run pytest
        run: pytest
