name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='ec2-ssh-key.pem' \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/my-app

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # SSH into the EC2 instance
            cd /home/ubuntu/my-app

            # Install Docker and Docker Compose
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Set Up Python Virtual Environment and Install Dependencies
            sudo apt-get install -y python3-venv
            python3 -m venv venv
            source venv/bin/activate
            pip install -r src/requirements.txt

            # Run Docker Compose on EC2
            docker-compose up -d
