name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Airflow Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-airflow-image:${{ github.sha }} -f src/Dockerfile.airflow .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-airflow-image:${{ github.sha }}

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='ec2-ssh-key.pem' \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/my-app

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # SSH into the EC2 instance
            cd /home/ubuntu/my-app

            # Clean up space
            docker system prune -a -f

            # Install Docker and Docker Compose
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Pull the Docker image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-airflow-image:${{ github.sha }}

            # Set Up Python Virtual Environment and Install Dependencies
            sudo apt-get install -y python3-venv
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/requirements.txt
            pip install --upgrade sqlalchemy
            alembic upgrade head

            # Update docker-compose.yml to use the new image
            sed -i 's|image: my-airflow-image|image: ${{ secrets.DOCKER_HUB_USERNAME }}/my-airflow-image:${{ github.sha }}|g' docker-compose.yml

            # Run Docker Compose on EC2
            docker-compose up -d
